# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('appointment_title', models.CharField(max_length=40)),
                ('appointment_description', models.TextField()),
                ('time_field', models.TimeField(blank=True, null=True)),
                ('date_field', models.DateField(blank=True, null=True)),
                ('address', models.CharField(max_length=250)),
                ('state', models.CharField(max_length=5)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=6)),
                ('phone', models.CharField(max_length=14)),
                ('notes', models.TextField()),
            ],
        ),
    ]
